package com.tayler.valushopping.utils

const val EMPTY_VALE = ""
const val NAME_VALE = "Bienvenid@s"
const val ID_DAFAUL = "0"

const val JSON_ITEM = "item.json"
const val JSON_ITEM_ADMIN = "item_admin.json"
const val JSON_ITEM_OTHER = "item_other.json"
const val PACKAGE_APP_WHATS_APP = "com.whatsapp"
const val PACKAGE_APP_WHATS_APP_BUSINESS = "com.whatsapp.w4b"
const val SCRIP_SINGLE  = "-"
const val SCRIP_DEFAULT  = "- - - - - - -"
const val SCRIP_MULTI  = "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
const val ID_MOVIE_DEFAULT = "beH6uqy6Xsw"
const val DIALOG_TITLE_DEFAULT = "Datos guardados"
const val DIALOG_MESSAGE_DEFAULT = "Datos guardados correctamente, los vera reflejado la proxima ves que ingrese."
const val TYPE_CLOTHES = "1"
const val TYPE_OTHER = "2"
const val LINK_TERM = "https://docs.google.com/uc?id=" + "1JOtkc5ksAuCWWd13wwwbtmNIYgefAfQ4" + "&export=download"
